### ISSUE TITLE
[NTR] New ontology term: dysplasia

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/ontology#100]
## Preferred term label

dysplasia

## Textual definition

A term used to describe the presence of abnormal cells within a tissue or organ. Dysplasia is not cancer, but it may sometimes become cancer.

## Suggested parent term

disease or disorder: MONDO:0000001

## Use case

Disease status of donor
Disease status of specimen from organism

**Comment by paolaroncaglia** [comment]
Hi @ami-day,
This one is a bit tricky - EFO has EFO:0008501 'dysplasia' in its disease branch, which HCAO does not import because it imports Mondo diseases instead. However, Mondo does not have a broad term for dysplasia, just specific ones (e.g. colon dysplasia). I'll take a look at the other ticket you linked to see if there's a publication or dataset in case a different term may be a reasonable alternative choice. Otherwise I think we'll need to request dysplasia to Mondo.

**Comment by paolaroncaglia** [comment]
@ami-day @ESapenaVentura 
The question is - is limbal dysplasia the same as Mondo 'limbal stem cell deficiency'? Possibly not. I looked up all the references I could find.
The relevant section in the paper Method is:
"The cornea with limbal dysplasia was obtained from a deceased..."
Based on this, I'd suggest to use MONDO:0021238 'cornea neoplasm'. Dysplasia is a form of neoplasm (consistently with your suggested definition, and classified that way in EFO). If you are unsure that the sample was neoplastic, you could use MONDO:0000942 'corneal disorder'. If you need a term to describe the sample, rather than any experiment that might have been done with limbal stem cells, you'd be fine. Using a broad term for 'dysplasia' would be much less specific in my opinion. 
Feel free to disagree - I'll be away for nearly a week but will pick this up on my return. Thank you.

**Comment by paolaroncaglia** [comment]
@ami-day @ESapenaVentura hi, following up on this after my trip. Please let me know if you need anything else from my side. Otherwise, feel free to close this ticket, thanks!

**Comment by ESapenaVentura** [comment]
Hi @paolaroncaglia , apologies I missed the first messages

I am not an expert on cancer or eye but I have looked up the definitions on dysplasia and neoplasm and I don't think dysplasia a form of neoplasm, but rather the contrary:

>Dysplasia: an increasing degree of disordered growth or maturation of the tissue (often thought to precede neoplasia) such as cervical dysplasia as a result of human papillomavirus infection. Dysplasia is still a reversible process. However, once the transformation to neoplasia has been made, the process is not reversible.
>
>Thus, there is a natural history from metaplasia to dysplasia to neoplasia. This is best evidenced in development of uterine cervix and respiratory tract neoplasms.

By this definition (extracted from [here](https://webpath.med.utah.edu/NEOHTML/NEOPL106.html#:~:text=Dysplasia%20is%20still%20a%20reversible,cervix%20and%20respiratory%20tract%20neoplasms.)), it looks like dysplasia can be considered a previous stage to a neoplasm, and may or may not evolve into a neoplasm

In this case, we are unsure that the sample was neoplasic so I don't think using that term would be accurate. Corneal disorder is very broad as well, which is not great.

It may be better to use the term "dysplasia", even though it's general, combined with the rest of the metadata (eye, limbal region) can give you a pretty accurate description of the disease status of the sample

However, to describe disease, we are restricted to use terms under the MONDO ontology. Can you think of any way forward with those requirements?

Many, many thanks for your help

**Comment by paolaroncaglia** [comment]
Hi @ESapenaVentura ,

Thanks for your feedback. My thoughts:

Focusing on currently available Mondo terms: MONDO:0045024 'cancer or benign tumour' is defined as "Any disorder that features _disrupted cell proliferation_. Includes hyperplasia, neoplastic syndrome and isolated neoplasm diseases as well as precancerous conditions.". The label suggests that the transition to neoplasia has occurred, but the definition sounds more inclusive. There are also some children if you'd like to take a look. Would this work for you?

Mondo used to have a term MONDO:0002001 'obsolete disease of cellular proliferation', which has been replaced by MONDO:0005070 'neoplasm'. Perhaps we could ask Mondo to broaden the label and definition of MONDO:0045024 'cancer or benign tumour' (the highest-level term directly under 'disease or disorder' that mentions cell proliferation) to explicitly mention proliferation disorders that don't necessarily develop into neoplasms. I'll see if there was any discussion in the Mondo tracker when they decided to obsolete the old term. If we go this route and Mondo agrees, you'd have to wait for the next Mondo release (early April, assuming they can fit in the change in time) and then the following HCAO release (April 20th).

The description of dysplasia above fits more with a phenotype than with a disease. This doesn't help because HCAO doesn't include phenotype terms. However, you could capture the concept of "disordered growth" using a combination of the following terms that are in HCAO: PATO:0000460 'abnormal' + GO:0040007 'growth', or GO:0008283 'cell population proliferation' or one of its children.
Or you could use just CL:0001061 'abnormal cell', which is also in HCAO.
These options capture the essence, but are not in the disease branch.
A term that fits very well with your needs but is in a branch that's currently unavailable to HCAO is HP:0031377 'Abnormal cell proliferation'. Note that my suggestion above of using 'abnormal' + 'cell population proliferation' is basically the same way that HP:0031377 'Abnormal cell proliferation' is built. Importing HP into HCAO would be very complex, and the effort would probably be disproportionate to the actual needs that HCA has of using phenotype terms, so I won't suggest that ;-)

EFO has EFO:0008501 'dysplasia' in its disease branch, it's placed as a child of neoplasm and its definition is modelled on the NCIt term, but both the definition and the comment point to phenotype really. Perhaps we could force HCAO to import EFO:0008501 'dysplasia' as a child of MONDO:0000001 'disease or disorder', but the definition would still not fit with your need (and I'm reluctant to change it in EFO because the term is problematic per se - both with regards to its placement as disease vs. phenotype and because it looks like the community usage is not 100% consensual when it comes to developing into neoplasms or not).

Not an easy case but we'll get there!

**Comment by ESapenaVentura** [comment]
thanks @paolaroncaglia , sincerely, it looks like incorporating dysplasia as a term may be too complicated, especially when we have only 1 known case of a project that would need this term

Given your message above, I am inclined to just accept "neoplasm" as a good enough substitute and consider this topic further if this ends up being a recurrent issue

What do you think @ami-day?

**Comment by paolaroncaglia** [comment]
@ESapenaVentura @ami-day hi,

> I am inclined to just accept "neoplasm" as a good enough substitute and consider this topic further if this ends up being a recurrent issue 

I'll go ahead and close this ticket then. Please feel free to open a new one if/when necessary (or re-open this one if you have any objection). Thank you both.
