### ISSUE TITLE
Adding spatial transcriptomics under library preparation [ENQ] 

### ISSUE THREAD

**Issue by idazucchi** [HumanCellAtlas/ontology#118]
Hi @zoependlington @bvarner-ebi
I'm not sure if you are ready to start integrating new terms into the HCAO, but I would like your opinion on this in the meanwhile.

We use the terms under [library preparation](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711) to indicate how the library was prepared. 
The only term for Spatial transcriptomics available under library preparation is Visium, which covers most but not all of the datasets we have encountered.
Would it be possible to get a generic Spatial transcriptomics term under library preparation, or even a branch with the different techiniques?

@ESapenaVentura to keep you updated

**Comment by bvarner-ebi** [comment]
Hi, @idazucchi, would using the class [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994) address your use case?

**Comment by idazucchi** [comment]
The term you are suggesting would be perfect as a general term, but we are restricted to using terms under [library preparation](http://purl.obolibrary.org/obo/OBI_0000711).
Right now [spatial transcriptomics](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008994) is in the HCAO but it's under assay, would it be possible to move or add it under library preparation?

**Comment by bvarner-ebi** [comment]
Hi, @idazucchi, would it have to be related with an "is a" relationship, i.e., 'spatial transcriptomics' **subclass of** 'library preparation'? 
I don't know if that statement is accurate.

Would 'spatial transcriptomics' **part of** 'library preparation' work, assuming that axiom is true?

**Comment by idazucchi** [comment]
Hi @bvarner-ebi,
The validation we do is based on SubclassOf so that is what we would need. I think that it also makes sense as a relationship since the spatial trascriptomics techniques are a kind of library preparation.

Is this possible?

**Comment by bvarner-ebi** [comment]
Hi, @idazucchi, thanks for the reply.

Pursuant to the comments above and after getting some additional feedback from @dosumis, I don't think it makes logical sense to place 'spatial transcriptomics' under 'library preparation'. Based on the definitions, 'spatial transcriptomics' does not seem to be a subclass of 'library preparation', but rather 'library preparation' is part of 'spatial transcriptomics' (I initially had this reversed). 

It may make sense to approach this by addressing "we are restricted to using terms under [library preparation](http://purl.obolibrary.org/obo/OBI_0000711)". Otherwise, it seems like we would have to model terms inaccurately to meet your use case, which would can lead to additional downstream effects for anyone using EFO.

**Comment by ESapenaVentura** [comment]
@bvarner-ebi , I understand your concerns, but just to go back and check on what we want:
- We have a dataset that used a non-general library preparation method, (non-visium).
- We want to describe the method for the library preparation protocol

The suggestion @idazucchi made above was because we had an internal discussion about what would be the best way to implement this new term we used, but are happy to discuss alternatives.

Currently, I don't understand why moving that term under library preparation (https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711) in the EFO slim of the HCAO would not be correct. We have several terms, including NanoString Digital Spatial profiling (https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030029) that are direct childs of that term in that branch. Could you explain why it would not be ok to consider, e.g. spatial transcriptomics by high-throughput sequencing (https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030005) as a term under library preparation?

And, if it really is incorrect, does that mean every term under library preparation that aludes to specific instances of each library preparation protocol (e.g. the NanoString one I mention above) be wrong?

(Also, it may be a case that spatial transcriptomics is too wide but spatial transcriptomics by high-throughput sequencing is not?)

Apologies for the long comment, I just want to make sure that we're coming across clear with our intentions and that we get the best possible outcome of this ticket!

**Comment by bvarner-ebi** [comment]
Hi, @ESapenaVentura,

Thank you for the information. Hopefully we can come up with a working solution.

> We have a dataset that used a non-general **library preparation method**, (non-visium).
> We want to describe the method for the **library preparation protocol**

This may be the point of confusion: my interpretation of the definition ['library preparation'](http://purl.obolibrary.org/obo/OBI_0000711) is different than 'library preparation method' or 'library preparation protocol'. 

It looks like 'library preparation' was copied from Ontology for Biomedical Investigations to EFO and then used with a different meaning in EFO (compare modelling in OBI). EFO has assays placed as subclasses under ['library preparation'](http://purl.obolibrary.org/obo/OBI_0000711), and that is the part that does not seem correct. My understanding is that these assays **have a step for 'library preparation' in their workflows**. If this is the case, I do not think it is correct to model assays as children (subclasses of) ['library preparation'](http://purl.obolibrary.org/obo/OBI_0000711).

>Could you explain why it would not be ok to consider, e.g. spatial transcriptomics by high-throughput sequencing (https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030005) as a term under library preparation?

Following from my comments above, I would say it is logically incorrect to say 'spatial transcriptomics by high-throughput sequencing' is a subclass of 'library preparation' if 'library preparation', as defined by the text definition, is actually a process that is one of many steps in 'spatial transcriptomics by high-throughput sequencing' (or any other assay). 

[The statement above](https://github.com/HumanCellAtlas/ontology/issues/118#issuecomment-1241953024): "since the spatial trascriptomics techniques are a kind of library preparation" -- this is where our perspectives differ.

If my conceptualisation of these classes is wrong, please do advise. If the perspective I outlined seems reasonable, may I suggest instead of pulling from children of ['library preparation'](http://purl.obolibrary.org/obo/OBI_0000711), you pull from ['assay'](http://purl.obolibrary.org/obo/OBI_0000070), as that modelling is less controversial. The remodelling of 'library preparation' in EFO could then be addressed at some point in time. Is that a reasonable way to proceed?

CC @dosumis

**Comment by rays22** [comment]
> Would it be possible to get a generic Spatial transcriptomics term under library preparation, or even a branch with the different techiniques?

I think it would be a good solution to add a **new** generic spatial transcriptomics term under library preparation.
See my explantation below. I hope this helps.

* * * *
Library preparation vs. assay
=============================

* There are three process types in the HCA [Metadata entity model](https://data.humancellatlas.org/metadata/structure):
    1. `sample preparation`: 'both the input and output of a process are biomaterials'. This looks like an [OBI:0000094 'material processing'](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000094&lang=en&viewMode=All&siblings=false).
    2. `assay`: 'the input is a biomaterial and the output is a file'. I think the HCA definition of *assay* matches quite well with the definition in EFO (from OBI): [A planned process with the objective to produce information about the material entity that is the evaluant, by physically examining it or its proxies.](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000070&lang=en&viewMode=All&siblings=false)
    3. `analysis`: 'both the input and output of a process are files, the unit represents an analysis'. This is not relevant to the current discussion.

Are the classes above meant to be disjoint? Are there any experimental processes that have multiple specified outputs, for example, both new biomaterials and information about the original biomaterials? Depending on your answer to these questions, your modelling of these processes can differ.

I think these terms are meant to be disjoint in HCA usage. If *library preparation* is a *sample preparation* process, then a *library preparation* term is not an *assay*, and that it why you can not use an *assay*-term from EFO in HCA library preparation-related metadata. @ESapenaVentura  please confirm this.

The [EFO:0008994 spatial transcriptomics](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0008994) term is defined as an *assay* in EFO. As the OBI and HCA definitions of *assay* appear to agree, and assuming that the HCA process types are meant to be disjoint, then it would be misleading and incorrect to include [EFO:0008994 spatial transcriptomics](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0008994) as a subclass of [OBI:0000711 library preparation](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711&lang=en&viewMode=All&siblings=false).

If there is actually any *assay*-type term included as a subclass of EFO/[OBI:0000711 library preparation](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711&lang=en&viewMode=All&siblings=false), then those should be double checked. If the specified output of a process (or a named series of processes) to which the term refers may include both information (file/files) and biomaterial, then the classification may not be correct for the HCA (assuming disjointness of terms 1-2).

I think if you add a new `library preparation for spatial transcriptomics` class under [OBI:0000711 library preparation](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711&lang=en&viewMode=All&siblings=false) in EFO that is clearly not an *assay* (the specified output is a biomaterial, not some data item), and follow a similar path for any other library preparation process term, even if a similar sounding *assay*-type term exists, then you have a solution that is logically coherent (without any major EFO/OBI restructuring) and would also work for the HCA.

**Comment by bvarner-ebi** [comment]
Thank you very much for the insight, @rays22.

If I follow correctly, you are suggesting that we create a new class called 'library preparation for spatial transcriptomics' as a subclass of 'library preparation'. 
HCA can then select library preparation protocols, but not assays, to be children of 'library preparation for spatial transcriptomics'.

@idazucchi, would that work for your use case?

**Comment by rays22** [comment]
> If I follow correctly, you are suggesting that we create a new class called 'library preparation for spatial transcriptomics' as a subclass of 'library preparation'.

Yes, that is what I am suggesting.

> HCA can then select library preparation protocols, but not assays, to be children of 'library preparation for spatial transcriptomics'. 

Just to clarify, HCA are allowed to select terms exclusively under 'library preparation' for their sample/library preparation type metadata annotations. If they pick an *assay*-type term, for example [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994), then they get a schema validation error. Correct me @idazucchi  or @ESapenaVentura if I am wrong here.

> Also, it sounds that it would be prudent to remove assay terms that are currently under 'library preparation'.

It depends. I think it may not be as urgent as adding the new library preparation term(s), because that seems to be a blocker for the HCA.

* On the one hand it is confusing to have assay terms under 'library preparation' if you do not want any overlap between [OBI:0000070 assay](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000070&lang=en&viewMode=All&siblings=false) (with data output) and [OBI:0000711 library preparation](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711&lang=en&viewMode=All&siblings=false) (biomaterial output).
* On the other hand, those assay terms from the library preparation branch do not appear to cause validation errors for HCA annotations at the moment, and I do not think that there is any formal logical disjointness asserted between [OBI:0000070 assay](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000070&lang=en&viewMode=All&siblings=false) and [OBI:0000711 library preparation](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711&lang=en&viewMode=All&siblings=false) in OBI or EFO. 

Again, correct me if I am wrong.

**Comment by bvarner-ebi** [comment]
I also very kindly received the following input from the author of ['library preparation'](http://purl.obolibrary.org/obo/OBI_0000711):

"... I agree with the suggestion of having a class ‘library preparation for spatial transcriptomics’ created, assuming that the output of this process is a ‘library’ (ie a material entity) that will be input to a ‘sequence data acquisition’. and as far as I recall, we (OBI) did not set disjointness explicitly between these classes (assay & ‘library preparation’). One question I ’d have is if there is a need to explicitly identify the ‘library material’ (the output of the library preparation process), for instance if these are logged in a ELN and stored in a -80C prior to loading onto a flowcell. hth."

@idazucchi, would you like to proceed with submitting a new term request for 'library preparation for spatial transcriptomics' if that will meet your use case?

**Comment by idazucchi** [comment]
Hi @bvarner-ebi and @rays22, thank you for your suggestions! We need a bit more time to discuss this within our team, is it ok if I get back to you next week?

**Comment by bvarner-ebi** [comment]
Sure, @idazucchi, absolutely. There is no blocker on my end.

**Comment by bvarner-ebi** [comment]
Great, @idazucchi. Would you kindly submit a "new term request" issue, and I will add the term accordingly.

**Comment by bvarner-ebi** [comment]
New term created (#121).
