### ISSUE TITLE
Add EDAM term for Protocol

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ontology#26]
For new term requests, please provide the following information:

## Preferred term label

Protocol

## Synonyms

None

## Textual definition

Information about how a scientific experiment or analysis was carried out that results in a specific set of data or results used for further analysis or to test a specific hypothesis.

[Citation](https://en.oxforddictionaries.com/definition/protocol)

## Suggested parent term

EDAM term under [Data](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_0006)

**Comment by daniwelter** [comment]
@malloryfreeberg In order to qualify for the data branch, especially at root level, the definition needs to be framed in relation to data. Please review.
See https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_2526 or https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_2042 for examples

**Comment by malloryfreeberg** [comment]
@daniwelter took a look at the examples you posted, and I updated the suggested definition. Do you think the definition now is more in line with the requirements for EDAM/Data?

**Comment by daniwelter** [comment]
@malloryfreeberg Any way we can get rid of procedure, or make it something like data about a procedure. I worry that with the current definition, the editors will reclassify protocol as an operation.

**Comment by malloryfreeberg** [comment]
@daniwelter how about now?

**Comment by daniwelter** [comment]
https://github.com/edamontology/edamontology/issues/402
