### ISSUE TITLE
Add term for surgeon and microsurgeon roles

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/ontology#36]
For new term requests

# 1. Surgeon

## Preferred term label

surgeon

## Synonyms

None

## Textual definition

A physician who performs surgical operations.

## Suggested parent term

[Organization role](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002012)

## Use case

A project may add a contributor that is a surgeon. Currently, have a dataset with this role for a contributor.

# 1. Microsurgeon

## Preferred term label

microsurgeon

## Synonyms

None

## Textual definition

A physician who performs surgery requiring an operating microscope.

## Suggested parent term

Child of the above proposed new surgeon term as this is a subtype of surgeon.

## Use case

A project may add a contributor that is a surgeon. Currently, have a dataset with this role for a contributor.

**Comment by daniwelter** [comment]
Would this use case not be covered by the existing [`clinician`](https://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009740) term?

**Comment by willrockout** [comment]
Yeah, that's what I was leaning towards but I thought it wasn't specific enough. You have a better idea on these than me so if you think it works I will use clinician.

**Comment by daniwelter** [comment]
Assuming this is for the contacts tab, unless there's a really compelling argument why users must know that this contributor is specifically a (micro)surgeon rather than a clinician in general (as opposed to an experimental scientist, computational scientist or PI), I don't think we need to capture this level of detail. I'd rather not set a precedent of becoming too detailed this early on or we may end up with submitters jumping up and down, insisting on very specific job titles. 

If you're happy with that, please close the ticket :)

**Comment by willrockout** [comment]
Works for me!
