### ISSUE TITLE
Help with ontology mappings for mouse endoderm dataset.

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#39]
Hi Dani  & Zoe,

Could you please help @willrockout and I map fields to the correct ontologies? We took a hack at a few, please let us know if they are incorrect.

MOUSE STRAIN = Afp - GFP

SPECIMEN_FROM_ORGANISM.ORGAN:

- whole embryos
- endoderm = UBERON:0000925 ?
- gut tube

SPECIMEN_FROM_ORGANISM.ORGAN_PART

- what would be the organ part if the organ is 'whole embryo'?
- parietal endoderm = UBERON:0008800 ?
- visceral and definitive endoderm = ___?___ and UBERON:0005439 ? 
- yolk sac endoderm = UBERON:0003257 ?

SELECTED CELL TYPE:

- Whole embryo cells
- Visceral endoderm cells
- Parietal endoderm cells
- Definite endoderm cells
- Yolk sac cells
- Visceral gut tube cells 
- Definite gut tube cells
- Anterior gut tube cells
- Posterior gut tube cells

**Comment by daniwelter** [comment]
Afp-GFP - needs to be added to EFO, please submit a new term request ticket.
whole embryos - UBERON:0000922
endoderm - UBERON:0000925
gut tube - UBERON:0001555 or UBERON:0007026 (presumptive gut) if it's for an embryo

organ part is not a required field and it doesn't make sense to fill it in for "whole embryo" since by definition the whole "structure" is used, not a sub-part
parietal endoderm - UBERON:0008800
visceral and definitive endoderm - UBERON:0004877 (needs importing in next release - please file a ticket) and UBERON:0005439
yolk sac endoderm - UBERON:0003257

The selected cell type terms requested don't really make sense to me as they aren't actually specific cell types, just the organ part followed by the word "cell". My understanding of the `selected_cell_type` field is that it is intended to highlight specific sub-populations of cells that were selected for by some process (eg FACS sorting) in the transition from specimen to cell suspension. I don't think it needs to be explicitly stated that if a specimen comes from the parietal endoderm, then the resulting cell suspension will contain parietal endoderm cells as no specific selection occurred for these cells during the dissociation process. Please provide additional information if my interpretation of the experimental design is incorrect.

**Comment by zoependlington** [comment]
I will move this ticket to done as the term requests required are in other tickets, but if anything else is needed @pnejad let me know and I'll move this ticket back.
