### ISSUE TITLE
Investigate appropriate ontology for preservation and storage methods

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#55]
In our metadata schema, we have the module [`preservation_storage.json`](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/biomaterial/preservation_storage.json) that has preservation method and storage method as enums. Ideally these should be ontologies but the EFO doesn't appear to have any terms for these methods. 

I'd like to find out whether we should be adding these terms to the EFO or importing them from another ontology. A few searches found that the ERO ontology seems to have some appropriate terms but they may not have enough detail for our purposes.

Once we figure out which ontology to use and appropriate terms are added to our HCAO then we can move forward with ontologising the terms in the metadata schema.

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,

Do you have a feeling for how many terms you'd need? EFO or HCAO don't import ERO terms atm, but we could create new EFO terms and xref ERO - that would also allow us to make the terms as specific as you'd need. @zoependlington could create a ROBOT template for you to provide info if that's helpful. Or let me know if you'd prefer to discuss this in person.

Thanks,
Paola

**Comment by mshadbolt** [comment]
Hi @paolaroncaglia I am not sure what a ROBOT template is.

Currently we have them as an enums with the following values:

```
"ambient temperature",
                "cut slide",
                "fresh",
                "frozen at -70C",
                "frozen at -80C",
                "frozen at -150C",
                "frozen in liquid nitrogen",
                "frozen in vapor phase",
                "paraffin block",
                "RNAlater at 4C",
                "RNAlater at 25C",
                "RNAlater at -20C"
"cryopreservation in liquid nitrogen (dead tissue)",
                "cryopreservation in dry ice (dead tissue)",
                "cryopreservation of live cells in liquid nitrogen",
                "cryopreservation, other",
                "formalin fixed, unbuffered",
                "formalin fixed, buffered",
                "formalin fixed and paraffin embedded",
                "hypothermic preservation media at 2-8C",
                "fresh"
```

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
Thanks for clarifying.
We could look at your list in terms of description of samples, rather than sample conservation/storage methods. Then the ‘specimen’ branch in EFO may be useful. I’m attaching a screenshot, see e.g. the existing terms’'RNAlater specimen’,’'fresh specimen’,’'frozen specimen’. Most terms are imported from OBI, but some are EFO. OBI itself doesn’t have more specific terms than those, but we could create EFO ones if you need detailed descriptions, e.g. EFO:NEW ‘frozen at -70C’ as a subclass of ‘frozen specimen’.

![Screen Shot 2020-11-05 at 17 15 25](https://user-images.githubusercontent.com/4982516/98266420-92933180-1f8a-11eb-960f-276dd9b018ad.png)

This may need more extended discussion, but it could be a start. Let us know what you think.

P.S. A ROBOT template is a special spreadsheet with pre-defined column headers where you can list ontology terms you need and input the usual information on them such as parents, definition etc. The template can then be used to add the terms to the ontology automatically rather than manually. It’s useful when you have several-to-many terms that need adding, as it’s quicker than editing the ontology manually.

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,

I'm reviewing tickets in this tracker, in view of my meeting with David and Zoë this afternoon. Please let me know if there's any update on this request, and/or if you have any comments on my suggestion [here](https://github.com/HumanCellAtlas/ontology/issues/55#issuecomment-722480152). If you'd prefer to discuss in person, we could add to the agenda for our next monthly curators meeting (Dec 9th). 

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,

Following up on my previous comment. If this discussion is still active/needed, I suspect that it may be more easily carried out in person, so feel free to add to the agenda for our next monthly curators meeting (Dec 9th). If the issue has been addressed or the discussion is no longer active, I guess the ticket may be closed. Meanwhile, I'll move it to the "Backlog" queue. Thanks!

Paola

**Comment by dosumis** [comment]
Zoe's call - but I think it makes sense to add EFO terms that subclass OBI.

**Comment by mshadbolt** [comment]
Hi @paolaroncaglia sorry for not replying to this sooner.

I think an ROBOT template would be great to be able to add the terms we need to EFO.

I should point out it isn't a huge priority for us right now so if you want to de-prioritise and I will come back and enquire again when we are making updates to the schema we could do that too.

**Comment by paolaroncaglia** [comment]
> Zoe's call - but I think it makes sense to add EFO terms that subclass OBI.

Update from today's curators call: @zoependlington agrees that it'd make sense to add EFO terms to describe storage/preservation methods (in terms of sample descriptions) as I suggested above. Summary plan (thanks @mshadbolt for confirming that it's not a huge priority):

- [ ] Paola to go back to the list in https://github.com/HumanCellAtlas/ontology/issues/55#issuecomment-722423929 and either a) assign an appropriate, existing term from the 'specimen' branch of EFO or b) suggest new terms and indicate appropriate parent in the 'specimen' branch of EFO. Depending on how many new terms are needed, either add them manually or work with @zoependlington towards a ROBOT template. Any new term should be tagged as "added_for_HCA". All of this should go in a (new) EFO ticket, referencing this one and tagging Marion.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
I reviewed the HCA enums in https://github.com/HumanCellAtlas/ontology/issues/55#issuecomment-722423929 and I drafted a [spreadsheet](https://docs.google.com/spreadsheets/d/1Wnok_nXEOXLjoGUu4lfeSMFZ5n1rysWu5Z1djrQaYBA/edit#gid=0) to map them to existing terms or to suggested new terms. Could you please take a look and let me know if you have any concern? Thanks.

**Comment by dosumis** [comment]
@rays22 to review.

**Comment by paolaroncaglia** [comment]
Hi @rays22 (cc @mshadbolt ),
Just a heads up that if you'd like those preservation/storage terms to be available in HCAO, they'll need to be created (and released) in EFO first. The next EFO release is scheduled for April 15th, and I'll need some advance warning to make sure that all terms are added in time. When you have a chance, could you please review my spreadsheet here https://docs.google.com/spreadsheets/d/1Wnok_nXEOXLjoGUu4lfeSMFZ5n1rysWu5Z1djrQaYBA/edit#gid=0 and comment if any of my suggested terms do not represent your existing metadata schema/module appropriately. Thanks.

**Comment by paolaroncaglia** [comment]
Hi @dosumis ,

> Note FBBI has some related terms -https://www.ebi.ac.uk/ols/ontologies/fbbi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbi_00000001&viewMode=All&siblings=false
> Might at least be worth xrefs to.

Some of those FBBI terms are not defined, but I'll add the following mappings unless you have any concern:

1. HCA 'cut slide' = FBbi:00000026 'sectioned tissue'
2. HCA 'paraffin block' = FBbi:00000020 'tissue in paraffin embedment'
3. HCA 'cryopreservation, other' = FBbi:00000013 'cryofixed tissue'
4. HCA 'formalin fixed, unbuffered', 'formalin fixed, buffered' and 'formalin fixed and paraffin embedded' are all more granular than FBbi:00000010 'formaldehyde fixed tissue', so that would be a broad mapping which I'd prefer to avoid.

Thanks,
Paola

**Comment by rays22** [comment]
It appears to me that some of the categories overlap. It is not always clear to me if we need separate terms for preservation and storage. [ metadata-schema/json_schema/module/biomaterial/preservation_storage.json "description": "Information relating to how a biomaterial was preserved and/or stored over a period of time."](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/biomaterial/preservation_storage.json)
For example, do we need separate terms for
1. `frozen in liquid nitrogen`
2. `cryopreservation in liquid nitrogen (dead tissue)`
3. `cryopreservation of live cells in liquid nitrogen`
?
Is there a consensus in the field what `dead tissue` would mean?

Other than maybe simplifying some of the categories, the [suggested terms and parent terms in the draft](https://docs.google.com/spreadsheets/d/1Wnok_nXEOXLjoGUu4lfeSMFZ5n1rysWu5Z1djrQaYBA) look sensible to me.

**Comment by paolaroncaglia** [comment]
Thanks @rays22 . In answer to your question "It is not always clear to me if we need separate terms for preservation and storage", to clarify, the labels and parents I suggest are in columns B and E respectively. I've "rephrased" all terms with a focus on the sample (specimen) description, rather than the preservation/storage method that the sample is subjected to. 
So the descriptions you list above would be represented as
'liquid nitrogen-frozen specimen' (where the focus is on _how_ the sample was frozen, to differentiate it from e.g. 'vapor phase-frozen specimen'
and
'frozen specimen preserved in liquid nitrogen (dead tissue)'
'frozen specimen preserved in liquid nitrogen (live cells)'
where the focus is on _what_ the specimen consists of (dead tissue vs. live cells). 
Personally I'm happy to have only the broader term 'liquid nitrogen-frozen specimen'; I included all terms in the spreadsheet that were in the json schema, on the grounds that if they were there they'd all be needed, but let me know if this is no longer the case. Thanks again for your feedback.
Paola

**Comment by paolaroncaglia** [comment]
Update: at curators mtg today, Ray mentioned that those terms are not urgent for HCA and would require changing their metadata schema. SCA do not get that type of info often. I'll move to Backlog.

**Comment by ESapenaVentura** [comment]
I have reviewed the conversation. It seems like we had a pretty laid out path to pursue this, but that it's going to take a lot of effort on the ontologists side(many new terms) and on the HCA side (Schema update + field migration for all entities in the HCA).

The value/cost is very low, at least for HCA. I don't know if SCEA would be interested in creating the terms anyways.

Nonetheless, what was discussed above is very valuable so, even though I think we can close this ticket, I am going to open a ticket in the metadata-schema repository and link to this, so we can use all the already-done research above when/if we prioritise this issue

**Comment by paolaroncaglia** [comment]
@ESapenaVentura thank you for following up. I'll close this ticket now; its content won't go lost, as your new ticket in the metadata-schema repo points to it.
