### ISSUE TITLE
[ENQ] What would be the correct ontology to use for mouse strain = NIH/Swiss?

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#79]
Our [dataset](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE117089) used NIH/3T3 cells that came from an NIH/Swiss strain embryo. What would be the correct EFO ontology to use here?
https://www.atcc.org/products/all/crl-1658.aspx

**Comment by paolaroncaglia** [comment]
Hi @pnejad,

The right term to use would be [EFO:0001222 NIH3T3](http://www.ebi.ac.uk/efo/EFO_0001222). It refers the same ATCC entry that you listed, but I’m guessing you couldn’t find it in EFO because of the different wording (NIH3T3 instead of NIH/3T3). 

@zoependlington 
@dosumis 
it seems that cell lines (i.e. descendants of CL:0000010 ’cultured cell’) are not imported in HCAO? They surely don’t have FMA xrefs, and by looking at their path up the EFO graph and at the efo_import and efo_slim files in https://github.com/ebi-ait/ontology/blob/master/src/ontology/, it seems to me that they wouldn’t be imported automatically. I can’t see cell lines in the [HCA OLS production instance](https://ontology.archive.data.humancellatlas.org/index). Have HCA wranglers not needed cell line terms before? If so, what’s the best strategy: a) can we import EFO:0001222 NIH3T3 alone, or b) do we have a good enough use case to justify importing the whole ‘cultured cell’ branch which is huge.

Meanwhile, I will edit EFO:0001222 NIH3T3 to add
- [ ] synonyms: NIH-3T3, NIH/3T3
- [ ] xref: CLO:0008172 (NIH-3T3 cell)

@pnejad 
Lastly, EFO:0001222 NIH3T3 is already linked to the anatomy term for “embryo”. It doesn’t refer the NIH/Swiss strain that the cell line came from, and that you mention, but the information can be gained from the ATCC reference if need be, so I wouldn’t worry about that.

Thanks,
Paola

**Comment by pnejad** [comment]
@paolaroncaglia Thank you for the detailed explanation!

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

For your request to annotate NIH/3T3 cells, @zoependlington imported CLO:0008172 (NIH-3T3 cell) into HCAO today. It will be visible in the [HCA OLS production instance](https://ontology.archive.data.humancellatlas.org/index) as soon as [this ticket](https://github.com/ebi-ait/hca-ebi-dev-team/issues/409) is addressed. 

Going forward, if/when you need more cell line terms, ideally we'd want to reference the domain ontology, CLO, if the term is available there. You may look terms up in https://www.ebi.ac.uk/ols/ontologies/clo and let us know that you'd like to import them - FYI, Zoe has set up the makefile for HCAO in that sense.

Thanks,
Paola
