### ISSUE TITLE
[ENQ] Chinese characters displaying in OLS?

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#85]
Hi 

I was just searching in the ols and came across this term which is displaying with chinese characters.

https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468

Not urgent or anything but thought it was a bit odd...

<img width="1174" alt="Screenshot 2021-05-17 at 20 50 09" src="https://user-images.githubusercontent.com/13007987/118476939-7bab7400-b751-11eb-897f-2f3bf46f6ec8.png">

**Comment by zoependlington** [comment]
I believe this is a known and fixed issue in OLS where, if a term had multiple labels of different language tags it wouldn't automatically pick the english one.

It looks fixed in the public version: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468

I think once the HCA OLS instance is updated to use the new code base, this will be rectified.

Tagging @henrietteharmse for confirmation.

**Comment by paolaroncaglia** [comment]
Thanks @zoependlington .
@mshadbolt , I believe that the issue was fixed in https://github.com/EBISPOT/OLS/issues/241.
@henrietteharmse , when you have a chance, could you please confirm , and suggest the best way forward for HCA curators?
Thank you all,
Paola

**Comment by henrietteharmse** [comment]
Yes @paolaroncaglia, @zoependlington is correct in that this issue has indeed been fixed on OLS. And yes, this is dependent on the HCA server being updated or another server being commissioned.

**Comment by paolaroncaglia** [comment]
Thanks @henrietteharmse .
I'm not sure if the HCA server issue has been formally reported (yet). If this is not the best tracker, could @mshadbolt or @dosumis open a ticket where appropriate, and close this one? Thanks!

**Comment by mshadbolt** [comment]
ok thanks for the response, I am not really sure about the progress on updating ols, will close this ticket anyways
