### ISSUE TITLE
[ENQ] Ontology for breast milk collection protocol

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#88]
From publicaiton 
"Milk collection protocols were approved by the Colorado Multiple Institution Review Board (COMIRB #14–1538) and all participants gave their informed consent. Briefly, mothers fasted overnight and while still fasting, collected a small aliquot of milk (<1 oz) at home in the morning, prior to a morning or early afternoon study visit. Samples were not standardized with regard to the time of feeding or pumping (i.e. before, during, after). Milk samples were placed in a cooler on ice and
transported to the study visit, at which point they were immediately transported to the laboratory from the clinic."

I'm assuming breast milk was pumped out, but I'm not sure what the best collection protocol ontology is for that?

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,
I assume you need a term in the 'process' branch, rather than in the 'protocol' branch, is that right? If so, I suggest creating a new EFO term as a child of 'planned process', named 'breast milk expression' or similar, and cross-referencing OMIT:0027908 'Breast Milk Expression'. I can add more details but let's clarify the 'protocol' aspect first please. Thank you!
Paola

**Comment by rachadele** [comment]
No, sorry if I wasn't more clear. I was wondering about the appropriate ontology term to use for 'collection protocol'. Right now we are just using 'biopsy'; does that work or is there a more specific ontology term for liquid collection?

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,
Thanks. To me 'biopsy' doesn't sound quite right, because it's implicit that someone other than the "sample organism", specifically a medical specialist, performs the biopsy/sample collection. ([Wikipedia](https://en.wikipedia.org/wiki/Biopsy): "A biopsy is a medical test commonly performed by a surgeon, interventional radiologist, or an interventional cardiologist. The process involves extraction of sample cells or tissues for examination to determine the presence or extent of a disease.") I think that a new term for 'breast milk collection' analogous to 'urine collection' would be more appropriate. It'd be a subclass of 'collecting specimen from organism'. I can create the new term in time for the next HCAO release (August 18th), but if you are in a hurry, I guess you could use 'collecting specimen from organism' (parent of 'biopsy') and then change to 'breast milk collection' as soon as it's available?

**Comment by rachadele** [comment]
Hi @paolaroncaglia,
Yes, we would be happy to use a new ontology. Thanks so much for offering to create one! We are fine with submitting this after the ontology is created, as long as it is in time for the next HCA release.

**Comment by rachadele** [comment]
@willrockout looping you into this

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,
Unless there are unexpected issues, the new term should be available to you a couple of days before your release. I'll be on leave August 16-24, so I'll outline the plan of action here now, so you know where/when to check:
I've moved the request for the new EFO term to the EFO tracker: https://github.com/EBISPOT/efo/issues/1200. I'll update that ticket when the new EFO ID is available, by the end of next week.   
The new EFO term will be public with the next EFO release (Aug. 16th).
The HCAO release is scheduled for Aug. 18th. It will import the new EFO term. Zoë (@zoependlington ) will take care of both the EFO and the HCAO releases. She will then ask the EBI HCA developers to deploy the HCAO release in the HCA OLS instance; I asked Zoë to tag you so you can follow when that's done - the term will then be available to you.
I'll close this ticket now, but if you have any question, please feel free to reopen/reach out.
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@rachadele one last question please:

> From publicaiton
> "Milk collection protocols were approved by the Colorado Multiple Institution Review Board (COMIRB #14–1538) and all participants gave their informed consent. Briefly, mothers fasted overnight and while still fasting, collected a small aliquot of milk (<1 oz) at home in the morning, prior to a morning or early afternoon study visit. Samples were not standardized with regard to the time of feeding or pumping (i.e. before, during, after). Milk samples were placed in a cooler on ice and
> transported to the study visit, at which point they were immediately transported to the laboratory from the clinic."

Could you provide the PMID of that publication, please? Thanks.

**Comment by paolaroncaglia** [comment]
@rachadele I'd also need your ORCID please (not mandatory, but nice to have so the new term can be "attributed" to you). Thanks.

**Comment by rachadele** [comment]
@paolaroncaglia 
PMID: 33216249
ORCID id: https://orcid.org/0000-0002-7431-4139
