### ISSUE TITLE
[ENQ] Please add 'frontotemporal lobar degeneration' and 'sporadic frontotemporal lobar degeneration' to MONDO

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/ontology#94]
Please add the following two terms to MONDO. We are wrangling GSE174332 for the HCA DCP and need these 2 terms for the disease field. The dataset is associated with this preprint: https://www.biorxiv.org/content/10.1101/2021.07.07.451374v2.full

frontotemporal lobar degeneration: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2916644/#:~:text=Frontotemporal%20lobar%20degeneration%20(FTLD)%20is,frontal%20and%20anterior%20temporal%20lobes.

sporadic frontotemporal lobar degeneration: https://pubmed.ncbi.nlm.nih.gov/31914219/

**Comment by pnejad** [comment]
Hi @paolaroncaglia  thank you for looking up our options. We can use 'Pick disease' for this dataset. If you are still interested in looking up the paper, the title is: Single-cell profiling of the human primary motor cortex in ALS and FTLD.

DOI: 10.1101/2021.07.07.451374

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

Thanks for your feedback. Now that I can access the full-text biorxiv preprint, I can't see any mention of Pick bodies there, so I'm questioning the appropriateness of using 'Pick disease' for the associated dataset. (I had pushed for that because the other reference you provided described Pick disease specifically, which is a subtype of frontotemporal dementia.) In the preprint, when authors mention FTLD, they reference [this paper](https://academic.oup.com/brain/article/134/9/2582/418398) "Motor Neuron dysfunction in frontotemporal dementia", so you could use the broad term [MONDO:0017276 frontotemporal dementia](http://purl.obolibrary.org/obo/MONDO_0017276), but that's a grouping term and we could probably do better. In the preprint, I'm now looking at the section "Methods - Human sample selection and preparation" that describes the patient samples in detail, and I'm hoping to find a specific appropriate disease term to use based on that. To be continued.

**Comment by paolaroncaglia** [comment]
Attaching screenshot of methods section as preprint takes forever to load

![Screen Shot 2021-11-05 at 10 41 29](https://user-images.githubusercontent.com/4982516/140490811-da749833-f264-4d28-ba62-7c79d87bd1ce.png)

**Comment by paolaroncaglia** [comment]
Summing up, the 4 patients cohort are characterized by:

1) sporadic ALS, TDP43, MND (motor neuron degeneration); no C9orf72-related pathology => may use [MONDO:0012790](http://purl.obolibrary.org/obo/MONDO_0012790)

2) ALS, TDP43, MND, C9orf72 => may use [MONDO:0007105](http://purl.obolibrary.org/obo/MONDO_0007105)

3) sporadic FTLD, TDP43; no MND, no C9orf72 => may use [MONDO:0011842](http://purl.obolibrary.org/obo/MONDO_0011842)

4) FTLD, TDP43, C9orf72; no MND => may still use [MONDO:0011842](http://purl.obolibrary.org/obo/MONDO_0011842)

Let me know if you disagree.

**Comment by pnejad** [comment]
Looks good to me! Thank you @paolaroncaglia

**Comment by paolaroncaglia** [comment]
@pnejad You're welcome. I'll close this ticket now.
