### ISSUE TITLE
[ITR] Nuclear RNA extract

### ISSUE THREAD

**Issue by rachadele** [HumanCellAtlas/ontology#95]
## Source ontology identifier
OBI:0000862

## Destination ontology
HCAO

## Preferred term label
nuclear RNA extract

## Textual definition

A RNA extract that is the output of an extraction process in which RNA molecules found in the nucleus, including mRNA precursors (pre-mRNA), are extracted.

## Suggested parent term

RNA extract 

## Use case

Used for input nucleic acid molecule in HCA library preparation schema

## Attribution

https://orcid.org/0000-0002-7431-4139

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,
What branch of the HCA ontology would you need the term to be in, please? Asking because the parent you suggest isn't in HCAO. There are RNA terms under 'biological macromolecule', but I'm not sure if that branch is compatible with the HCA library preparation schema. I'm attaching a screenshot. Thanks.

![Screen Shot 2021-11-08 at 18 31 24](https://user-images.githubusercontent.com/4982516/140790359-bcbad364-6701-4e1c-b010-9dffe8374c4f.png)

**Comment by rachadele** [comment]
I think it should go under "RNA". Sorry for the confusion!

**Comment by paolaroncaglia** [comment]
@rachadele 
Thanks, I'll create an EFO term for this, so I've moved the task to an [EFO ticket](https://github.com/EBISPOT/efo/issues/1341) and I'll close this one.
