### ISSUE TITLE
Ontology term for Cell Barcode files

### ISSUE THREAD

**Issue by ipediez** [HumanCellAtlas/ontology#97]
Hi! 

We've been discussing at the HCA wrangler meetings about the best ontology choice for different file types that we work with. One of them is particularly difficult and it might need a new ontology term: the Cell Barcodes files coming from 10X sequencing. 

Those files contain a list of the cell barcodes in the experiment, which are unique identifiers of each one of the cells analyzed in that experiment. They are combined with a file containing a list of genes (which we tag as a feature table, data:1270) and a file containing the expression values and the links to the gene and the barcodes files (which we tag as a count matrix, data:3917). Until now, we've been tagging cell barcodes files as Molecular property Identifier (data:2110), but we've realized that this term is related to Molecular property (data:2087), defined as "A report on the physical (e.g. structural) or chemical properties of molecules, or parts of a molecule". A cell barcode is a nucleic acid sequence identifying an individual cell, therefore Molecular property identifier does not seem the right choice. 

We've been looking at the ontologies and haven't found a term that we could use.

Do you have some term suggestions, or is it better to create a new term? In case a new term is needed, how much do you think it would take to release it?

**Comment by paolaroncaglia** [comment]
Hi @ipediez (cc @zoependlington and @pnejad ),

Thanks for providing informative details. EFO has EFO:0010198 'cell barcode' ("A short nucleotide sequence that is added during a single cell library preparation to identify reads from an individual cell."), along with other terms related to cell barcode that may be useful (see a list [here](https://www.ebi.ac.uk/ols/search?q=cell+barcode&ontology=efo)). However, EFO:0010198 'cell barcode' isn't currently available to HCA because it's a descendant of 'single cell information', itself a child of 'information entity', a branch that isn't currently part of the EFO subset for HCA. I suspect that several terms in the branch that starts at 'single cell information' may be useful to HCA; I attach a screenshot below, and you may further explore the branch [here](http://www.ebi.ac.uk/efo/EFO_0010185).
My suggestion would be to include the 'single cell information' branch in the EFO subset for HCA (if not the whole 'information entity' branch). However, I wonder if there are reasons why this wasn't done at the "onset" of the HCA application ontology. There may have been previous discussion before I joined the project. 
@zoependlington , please comment if you're aware of any constraint to that inclusion (other than ontology size); if not, would it be possible to modify the HCAO build pipeline in time for the next HCAO release (scheduled for Feb 16th)? That would make 'cell barcode' available HCA wranglers ~Feb 18th.
@ipediez and @pnejad , please comment on any constraint from the HCA pipeline side - I'm not too clear on where you'd expect the 'cell barcode' term to be placed in the ontology. If I understand correctly, you've been using an EDAM term so far, but you mentioned that it may not be the right choice.

![Screenshot 2022-02-02 at 12 16 46](https://user-images.githubusercontent.com/4982516/152143835-fbf037ca-27dc-4a82-800d-422a0af8556b.png)

**Comment by zoependlington** [comment]
@paolaroncaglia We can certainly extend the EFO slim that's released with the HCAO releases, I'm not aware of any reason why we couldn't!

**Comment by ESapenaVentura** [comment]
@paolaroncaglia same here, as I understood the HCAO slim serves exactly for this purpose :) 

Our only constraint is that we would need to update the metadata schema to allow for these terms to be validated.

About what you comment on the hierarchy, not sure either. Maybe @pnejad has a better thought on this, but I don't see why not include the whole "information entity" branch. It does seem to contain quite useful terms, even if they don't serve of any use for us right now.

**Comment by pnejad** [comment]
@ESapenaVentura Do you mean updating the metadata schema to allow validation of EFO ontologies for content descriptions (which currently only allows EDAM ontologies)?

**Comment by ESapenaVentura** [comment]
Spot on @pnejad 💯  that is exactly what I meant

**Comment by paolaroncaglia** [comment]
Hi @ipediez @pnejad @ESapenaVentura 
cc @zoependlington @dosumis 
Summing up, 
- [ ] @zoependlington will kindly extend the EFO slim for HCA, in time for the next HCAO release, to include the whole "information entity" branch; (Zoë, please let me know if I can help in any way, thank you!)
- [ ] @ESapenaVentura and/or @pnejad will ensure that the HCA metadata schema is updated to allow validation of EFO ontology classes for content descriptions.

Please comment if you have any concern or additional suggestion. Otherwise, I'll update this ticket after the next HCAO release.

**Comment by dosumis** [comment]
We could add the whole 'single cell information branch' here:

https://github.com/HumanCellAtlas/metadata-schema/blob/ad20343b331abdde586037605ea091af38f2554e/json_schema/module/ontology/file_content_ontology.json#L30

This could work:

```json
            "graph_restriction":  {
                "ontologies" : ["obo:edam", "obo:EFO"],
                "classes": ["data:0006", "EFO:0010185" ],
                "relations": ["rdfs:subClassOf"],
                "direct": false,
                "include_self": false
            },
```

@zoependlington to add branch to HCAO.  This needs to happen before the metadata schema is modified.

**Comment by pnejad** [comment]
@zoependlington Please go ahead and add single cell information branch to HCAO :)

**Comment by zoependlington** [comment]
Will do @pnejad! Thanks for confirming 😁

**Comment by paolaroncaglia** [comment]
Hi @ipediez @pnejad @ESapenaVentura,

The whole 'information entity' branch, including child 'single cell information' and descendant 'cell barcode', is now in the HCA application ontology.
It can be browsed [here](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000030).

As agreed, you should now please ensure that the HCA metadata schema is updated to allow validation of EFO ontology classes for content descriptions. Should this task be recorded somewhere else? If so, this ticket may be closed. Thank you.

Paola

**Comment by paolaroncaglia** [comment]
@ipediez (cc @pnejad and @ESapenaVentura ) Based on a [separate, more recent ticket](https://github.com/HumanCellAtlas/ontology/issues/101), I trust that the HCA metadata schema now allows validation of terms in the 'information entity' branch, so I'll close this ticket. Thanks.
